// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCsjuJPWfxezcEISPj1HxhxflZ6WEd6J8',
    appId: '1:666957697784:web:555e1a6dd43acd03db610d',
    messagingSenderId: '666957697784',
    projectId: 'timetrader-83265',
    authDomain: 'timetrader-83265.firebaseapp.com',
    storageBucket: 'timetrader-83265.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCsjuJPWfxezcEISPj1HxhxflZ6WEd6J8',
    appId: '1:666957697784:android:555e1a6dd43acd03db610d',
    messagingSenderId: '666957697784',
    projectId: 'timetrader-83265',
    storageBucket: 'timetrader-83265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCsjuJPWfxezcEISPj1HxhxflZ6WEd6J8',
    appId: '1:666957697784:ios:555e1a6dd43acd03db610d',
    messagingSenderId: '666957697784',
    projectId: 'timetrader-83265',
    storageBucket: 'timetrader-83265.firebasestorage.app',
    iosBundleId: 'com.example.timetrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCsjuJPWfxezcEISPj1HxhxflZ6WEd6J8',
    appId: '1:666957697784:ios:555e1a6dd43acd03db610d',
    messagingSenderId: '666957697784',
    projectId: 'timetrader-83265',
    storageBucket: 'timetrader-83265.firebasestorage.app',
    iosBundleId: 'com.example.timetrader',
  );
} 